### ISSUE TITLE
relative path can't be expressed as a file URI

### ISSUE THREAD

**Issue by krisgesling** [dwfalk/rhythmbox-skill#1]
Hi dwfalk,

Thanks for creating a Rhythmbox Skill for Mycroft. I just installed it and tried giving it a spin with the utterance: "Play something by 360"
> "Just a second"
> selecting artist
> An error occurred while processing a request in Rhythmbox Skill.

```
Traceback (most recent call last):
  File "/home/kris/mycroft-core/mycroft/skills/core.py", line 1039, in wrapper
    handler(message)
  File "/home/kris/mycroft-core/mycroft/skills/common_play_skill.py", line 126, in __handle_play_start
    self.CPS_start(phrase, data)
  File "/opt/mycroft/skills/rhythmbox-skill.dwfalk/__init__.py", line 96, in CPS_start
    self._play_artist(data['artist'])
  File "/opt/mycroft/skills/rhythmbox-skill.dwfalk/__init__.py", line 250, in _play_artist
    uri = pathlib.Path(y).as_uri()
  File "/usr/lib/python3.7/pathlib.py", line 723, in as_uri
    raise ValueError("relative path can't be expressed as a file URI")
ValueError: relative path can't be expressed as a file URI
```

Perhaps something like [os.path.expanduser](https://docs.python.org/3.6/library/os.path.html#os.path.expanduser) is needed?
We discourage accessing the file system outside of the skill-specific namespace which is usally handled by [mycroft.filesystem](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/filesystem/__init__.py) however this is clearly a case where it's required.

Also wanted to let you know about requirements.txt, this is where you can add required packages like fuzzywuzzy and they'll be installed automatically when people run:
`mycroft-msm install https://github.com/dwfalk/rhythmbox-skill`
This is also how it will work if you submit the skill to the Marketplace and people install it via voice.

If you have no version requirements you can just write the package name, or you can specify minimum or specific versions. See the [weather skill for an example](https://github.com/MycroftAI/skill-weather/blob/d93822ed1a64cc7ae88a5a0fe515c741acf5125e/requirements.txt).

**Comment by dwfalk** [comment]
Thank you for the feedback and guidance.  I'll see what I can work up.  I'm using [os.path.expanduser](https://docs.python.org/3.6/library/os.path.html#os.path.expanduser) to query the Rhythmbox database, but didn't anticipate relative paths within the song locations.  Shouldn't be too difficult to tweak.   Oh, and thanks for pulling down the skill and testing.  Much appreciated.

**Comment by dwfalk** [comment]
I'm having fun trying to get Rhythmbox to accept a relative path.  Rather than guessing, would you be willing to share the location recorded for the 360 song in ~/.local/share/rhythmbox/rhythmdb.xml?  
For example, here is a path I have, albeit absolute, for one of my songs:

`<location>file:///home/don/Music/My%20Music/iTunes/iTunes%20Music/Linda%20Ronstadt/Greatest%20Hits%20(Remastered)/09%20It's%20So%20Easy.m4a</location>`

**Comment by krisgesling** [comment]
Sorry my bad, it turns out the track I picked is on a local file server:
`smb://192.168.1.199/media/Music/Triple%20J%20Hottest%202012/035.%20360%20-%20Run%20Alone.mp3`

It worked fine for a locally hosted file :blush:

**Comment by dwfalk** [comment]
Release 1.0.2 now does an "isabs" test against song locations to circumvent the skill from crashing.
